### PR TITLE
Migrate changes file

### PR DESCRIPTION
**Pull request by smarlowucf**
- Add Makefile for versino changes
- Create tags from bumpversion

### CODE REVIEW

**Review by rjschwei — APPROVED** [review]

**Comment by rjschwei** [comment]
I am OK with this. That said, this change comes with the caveat that bugzilla numbers will need to be in the git log. IMHO that is not a problem, we just have to remember or there will be a lot of history re-writing. If bugzilla entries get forgotten then what gets accepted in the build service and what gets generated will drift and will require manual work. 

Bottom line, the changelog generation imposes our distribution changelog rules onto the git changelog. Again, I am OK with it but we need to be aware of this side effect and go down the path with open eyes.

**Comment by smarlowucf** [comment]
It shouldn't really drift in that case because the changelog is being pulled from git. To fix a missing bugzilla entry you would change it in source.

**Comment by rjschwei** [comment]
> It shouldn't really drift in that case because the changelog is being pulled from git. To fix a missing bugzilla entry you would change it in source.

That's my point about re-writing history. If the bugzilla reference gets forgotten 3 commits back then the reference needs to be added to that commit comment, so history gets re-written. We just need to remember that for this project, or any others that get configured like this the rules for changelogs in the build service apply to the git commit messages.

**Comment by smarlowucf** [comment]
Fair enough I think this would only affect a small number of packages that we setup with obs_scm.

**Pull request merged**
